import { Technician, Ticket } from "@/types/domain";

export const demoTechnicians: Technician[] = [
  {
    id: "TECH-001",
    name: "Juan Perez",
    email: "juan.perez@company.com",
    phone: "+56 9 1111 1111",
    password: "tech123",
    active: true,
  },
  {
    id: "TECH-002",
    name: "Ana Gonzalez",
    email: "ana.gonzalez@company.com",
    phone: "+56 9 2222 2222",
    password: "tech123",
    active: true,
  },
  {
    id: "TECH-003",
    name: "Carlos Rodriguez",
    email: "carlos.rodriguez@company.com",
    phone: "+56 9 3333 3333",
    password: "tech123",
    active: true,
  },
  {
    id: "TECH-004",
    name: "Sandra Martinez",
    email: "sandra.martinez@company.com",
    phone: "+56 9 4444 4444",
    password: "tech123",
    active: true,
  },
];

export const demoTickets: Ticket[] = [
  {
    id: "ST-001",
    ticket_type: "support",
    title: "Falla de conectividad en sucursal",
    description: "Cliente reporta intermitencia en red interna y puntos de venta.",
    address: "Av. Libertador 1024, Santiago",
    status: "in_progress",
    priority: "high",
    scheduled_date: new Date().toISOString(),
    technician_id: "TECH-001",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    sla_deadline: new Date(Date.now() + 7200000).toISOString(),
    sla_status: "warning",
  },
  {
    id: "INS-001",
    ticket_type: "installation",
    title: "Mantenimiento preventivo CCTV",
    description: "Revision mensual de camaras y respaldo de grabaciones.",
    address: "Camino El Alba 445, Las Condes",
    status: "pending",
    priority: "medium",
    scheduled_date: new Date(Date.now() + 86400000).toISOString(),
    technician_id: "TECH-002",
    created_at: new Date().toISOString(),
    sla_deadline: new Date(Date.now() + 28800000).toISOString(),
    sla_status: "healthy",
  },
  {
    id: "ST-002",
    ticket_type: "support",
    title: "Problema en sistema de caja",
    description: "POS no comunica con servidor central, ventas pausadas.",
    address: "Mall Paseo Centro, La Florida",
    status: "assigned",
    priority: "high",
    scheduled_date: new Date(Date.now() - 7200000).toISOString(),
    technician_id: "TECH-003",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    sla_deadline: new Date(Date.now() - 1800000).toISOString(),
    sla_status: "critical",
  },
  {
    id: "RT-001",
    ticket_type: "removal",
    title: "Retiro de equipos antiguos",
    description: "Desinstalacion de switches viejos y reciclaje.",
    address: "Bodega Sur 2A, Quilicura",
    status: "pending",
    priority: "low",
    scheduled_date: new Date(Date.now() + 172800000).toISOString(),
    technician_id: "TECH-004",
    created_at: new Date().toISOString(),
    sla_deadline: new Date(Date.now() + 86400000).toISOString(),
    sla_status: "healthy",
  },
  {
    id: "INS-002",
    ticket_type: "installation",
    title: "Instalacion de fibra optica",
    description: "Primera fase de tendido de fibra en el sector.",
    address: "Av. Estanislao del Campo 3500, Independencia",
    status: "completed",
    priority: "medium",
    scheduled_date: new Date(Date.now() - 86400000).toISOString(),
    technician_id: "TECH-001",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    sla_deadline: new Date(Date.now() - 3600000).toISOString(),
    sla_status: "healthy",
  },
  {
    id: "ST-003",
    ticket_type: "support",
    title: "Caida de servidores datacenter",
    description: "Falla en UPS y falta de redundancia en alimentacion.",
    address: "Centro de Datos, Maipo",
    status: "in_progress",
    priority: "high",
    scheduled_date: new Date().toISOString(),
    technician_id: "TECH-002",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    sla_deadline: new Date(Date.now() + 3600000).toISOString(),
    sla_status: "warning",
  },
];
